<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOMnLVxa\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOMnLVxa/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOMnLVxa.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOMnLVxa\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerOMnLVxa\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'OMnLVxa',
    'container.build_id' => '1f8b2473',
    'container.build_time' => 1624886909,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOMnLVxa');
