<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGieKstj\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGieKstj/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGieKstj.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGieKstj\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerGieKstj\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'GieKstj',
    'container.build_id' => 'e6465d28',
    'container.build_time' => 1626781904,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGieKstj');
