<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJDGpX8T\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJDGpX8T/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJDGpX8T.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJDGpX8T\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerJDGpX8T\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'JDGpX8T',
    'container.build_id' => 'd44406c0',
    'container.build_time' => 1627380372,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJDGpX8T');
