<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP3GJxs5\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP3GJxs5/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP3GJxs5.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP3GJxs5\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerP3GJxs5\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'P3GJxs5',
    'container.build_id' => 'ef12117d',
    'container.build_time' => 1624886902,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP3GJxs5');
