<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG8JtOWq\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG8JtOWq/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG8JtOWq.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG8JtOWq\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerG8JtOWq\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'G8JtOWq',
    'container.build_id' => 'f369cd43',
    'container.build_time' => 1625055231,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG8JtOWq');
