<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container40V76cb\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container40V76cb/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container40V76cb.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container40V76cb\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \Container40V76cb\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => '40V76cb',
    'container.build_id' => '6a71468a',
    'container.build_time' => 1625007112,
], __DIR__.\DIRECTORY_SEPARATOR.'Container40V76cb');
