<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNQFTlPx\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNQFTlPx/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNQFTlPx.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNQFTlPx\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerNQFTlPx\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'NQFTlPx',
    'container.build_id' => '435da168',
    'container.build_time' => 1625120467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNQFTlPx');
