<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGeNeT0Q\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGeNeT0Q/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGeNeT0Q.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGeNeT0Q\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerGeNeT0Q\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'GeNeT0Q',
    'container.build_id' => '4da0b176',
    'container.build_time' => 1624886787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGeNeT0Q');
