<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX5zNgVP\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX5zNgVP/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX5zNgVP.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX5zNgVP\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerX5zNgVP\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'X5zNgVP',
    'container.build_id' => '5dc981ba',
    'container.build_time' => 1625469245,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX5zNgVP');
