<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX256jTC\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX256jTC/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX256jTC.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX256jTC\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerX256jTC\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'X256jTC',
    'container.build_id' => '531e729f',
    'container.build_time' => 1624886726,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX256jTC');
